# Generated by Django 4.0.4 on 2022-05-22 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hall_reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('comment', models.TextField()),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hall_reservation.hall')),
            ],
            options={
                'unique_together': {('date', 'hall_id')},
            },
        ),
    ]
