# Generated by Django 4.0.4 on 2022-07-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall_reservation', '0002_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='hall_id',
            new_name='hall',
        ),
    ]
